# Generated by Django 4.0.1 on 2022-01-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
