# Generated by Django 4.0.1 on 2022-01-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_products_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='owner',
        ),
    ]
