# Generated by Django 4.0.1 on 2022-01-27 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produits', '0005_remove_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
