# Generated by Django 4.0.1 on 2022-01-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecules',
            name='plants',
            field=models.ManyToManyField(null=True, to='plants.Plants'),
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('molecules', models.ManyToManyField(null=True, to='plants.Molecules')),
                ('plants', models.ManyToManyField(to='plants.Plants')),
            ],
        ),
    ]
