# Generated by Django 4.0.1 on 2022-01-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_molecules_plants_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecules',
            name='structure',
        ),
        migrations.AddField(
            model_name='molecules',
            name='structure_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='molecules',
            field=models.ManyToManyField(related_name='molecules_in_diseases', to='plants.Molecules'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='plants',
            field=models.ManyToManyField(related_name='plants_in_diseases', to='plants.Plants'),
        ),
        migrations.AlterField(
            model_name='molecules',
            name='plants',
            field=models.ManyToManyField(related_name='molecules_in_plants', to='plants.Plants'),
        ),
    ]
