# Generated by Django 4.0.1 on 2022-01-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_molecules_structure_molecules_structure_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='height',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='list_date',
        ),
        migrations.AddField(
            model_name='plants',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
