# Generated by Django 4.0.1 on 2022-01-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plants_height_remove_plants_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='molecules',
        ),
        migrations.RemoveField(
            model_name='diseases',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='molecules',
            name='plants',
        ),
        migrations.AddField(
            model_name='plants',
            name='diseases',
            field=models.ManyToManyField(related_name='plants_in_diseases', to='plants.Diseases'),
        ),
        migrations.AddField(
            model_name='plants',
            name='molecules',
            field=models.ManyToManyField(related_name='molecules_in_plants', to='plants.Molecules'),
        ),
        migrations.AddField(
            model_name='plants',
            name='synonyms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plants.family'),
        ),
    ]
