# Generated by Django 4.0.1 on 2022-01-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_diseases_molecules_remove_diseases_plants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecules',
            name='description',
        ),
        migrations.RemoveField(
            model_name='molecules',
            name='structure_url',
        ),
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='molecules',
            name='name',
            field=models.TextField(max_length=900),
        ),
    ]
