# Generated by Django 4.0.1 on 2022-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_molecules_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.TextField(),
        ),
    ]
