# Generated by Django 4.0.1 on 2022-01-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_diseases_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diseases',
            new_name='EconomicComments',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='description',
            new_name='generalDescription',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='synonyms',
            new_name='primaryCommonName',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='name',
            new_name='scientificName',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='diseases',
        ),
        migrations.AddField(
            model_name='plants',
            name='economicComments',
            field=models.ManyToManyField(related_name='plants_in_diseases', to='plants.EconomicComments'),
        ),
    ]
